"""Compose one `run-spec/1` document from layer files (rules version `compose/1`).

A run is authored as layers and composed into the single run spec MANIFOLD receives. This is the reference for
a MANIFOLD input constructor: what composes here, and passes the run-spec checks, is what that constructor
should accept. The conformance vectors in `manifold_contracts/vectors/compose/` are its test.

Layers, under one root (`manifold_run_specs/`), each owning disjoint members of the composed spec:

  recipes/<name>.yaml          compose, meta, settings, fidelity, and the names of the other layers:
                               sensor (a sensor-library file), scenario, engine_profile
  scenarios/<name>.yaml        collection                  -> descriptor.collection
  engine_profiles/<name>.yaml  origin, extras, engine      -> descriptor.origin, descriptor.extras, engine
  <sensor library>/<file>      the sensor-spec/1 document  -> descriptor.sensor (a ref, or inline)

The sensor library defaults to `manifold_sensors/`, the sibling of the root (as `run_spec.default_sensor_library`).

Rules: a member present in two layers is an error, not a merge, unless it is in `OVERRIDABLE` (empty). A
`settings` member whose `entry_id` names no entry of the sensor is an error (it is dropped only when a recipe
names several sensors, which `compose/1` does not yet allow). The composed settings follow the sensor's entry
order. The `roi` check of `run_spec` applies to the composed spec. No key is added to the descriptor outside
what the layers hold; layer provenance (file and hash per member) is returned by `explain`, never written into
the spec. Errors name the layer file and the field in it, never a path in the composed document.
"""
import copy
from pathlib import Path

import yaml

from protodirsig.run_spec import RunSpecError, _check_settings_roi, load_sensor_spec
from protodirsig.spectral import sha256_file

RULES = "compose/1"
SPEC_VERSION = "run-spec/1"
# Composed member -> the layer that owns it. `descriptor.<m>` unless noted.
OWNER = {"meta": "recipe", "settings": "recipe", "fidelity": "recipe", "sensor": "recipe",
         "collection": "scenario", "origin": "engine_profile", "extras": "engine_profile", "engine": "engine_profile"}
REQUIRED = {"recipe": ("compose", "meta", "sensor", "scenario", "engine_profile", "settings", "fidelity"),
            "scenario": ("collection",), "engine_profile": ("origin", "engine")}
CONTROL = {"recipe": ("compose", "scenario", "engine_profile")}     # recipe keys that name layers, not members
OVERRIDABLE = frozenset()                                          # members two layers may both hold; none yet
DESCRIPTOR_ORDER = ("meta", "origin", "collection", "sensor", "settings", "fidelity", "extras")
LAYER_DIR = {"scenario": "scenarios", "engine_profile": "engine_profiles"}
HEADER = "# GENERATED by scripts/compose.py from {recipe} - do not edit\n"


class ComposeError(RunSpecError):
    """A layer that does not compose. `layer` is the layer file (root-relative), `field` the field in it."""

    def __init__(self, layer, field, message):
        self.layer, self.field = str(layer), field
        super().__init__(f"{self.layer}: {field}: {message}" if field else f"{self.layer}: {message}")


def _load_layer(path, rel):
    if not path.is_file():
        raise ComposeError(rel, None, "not found")
    try:
        doc = yaml.safe_load(path.read_text())
    except yaml.YAMLError as e:
        raise ComposeError(rel, None, f"does not parse: {e}") from e
    if not isinstance(doc, dict):
        raise ComposeError(rel, None, f"expected a mapping, got {type(doc).__name__}")
    return doc


def merge(layers, sensor_ref, sensor_doc=None, inline_sensor=False):
    """The composition: `layers` maps `recipe`, `scenario`, `engine_profile` to `(name, doc)`; `sensor_ref` is the
    `{name, content_hash}` the recipe's sensor resolves to, `sensor_doc` the loaded sensor-spec (None skips the
    entry checks, for `run_spec.derive_run_spec`). Returns `(spec, sources)`, `sources` mapping each composed
    member to the layer name it came from."""
    held = {}                                                      # member -> [layer kinds holding it]
    for kind, (name, doc) in layers.items():
        for key in doc:
            if key in CONTROL.get(kind, ()):
                continue
            if key not in OWNER:
                raise ComposeError(name, key, f"unknown key; a {kind.replace('_', ' ')} holds "
                                   f"{sorted(m for m, o in OWNER.items() if o == kind) + list(CONTROL.get(kind, ()))}")
            held.setdefault(key, []).append(kind)
        for key in REQUIRED[kind]:
            if key not in doc:
                raise ComposeError(name, key, "missing")
    for member, kinds in held.items():
        if len(kinds) > 1 and member not in OVERRIDABLE:
            other = next(k for k in kinds if k != OWNER[member])
            raise ComposeError(layers[other][0], member, f"also in {layers[OWNER[member]][0]}; layers own disjoint "
                               f"members (this one belongs to the {OWNER[member].replace('_', ' ')})")
        if kinds[0] != OWNER[member]:
            raise ComposeError(layers[kinds[0]][0], member,
                               f"belongs to the {OWNER[member].replace('_', ' ')}, not the {kinds[0].replace('_', ' ')}")
    recipe_name, recipe = layers["recipe"]
    if recipe["compose"] != RULES:
        raise ComposeError(recipe_name, "compose", f"is {recipe['compose']!r}; this composer implements {RULES!r}")
    meta = recipe["meta"]
    if not isinstance(meta, dict) or not isinstance(meta.get("name"), str):
        raise ComposeError(recipe_name, "meta.name", "missing or not a string")
    settings = recipe["settings"]
    if not isinstance(settings, list) or not all(isinstance(s, dict) for s in settings):
        raise ComposeError(recipe_name, "settings", "must be a list of mappings keyed by entry_id")

    if sensor_doc is not None:
        entries = [e["entry_id"] for e in sensor_doc["sensor"]["entries"]]
        by_entry = {}
        for i, s in enumerate(settings):
            eid = s.get("entry_id")
            if eid not in entries:
                raise ComposeError(recipe_name, f"settings[{i}].entry_id",
                                   f"{eid!r} names no entry of sensor {sensor_ref['name']} ({entries})")
            if eid in by_entry:
                raise ComposeError(recipe_name, f"settings[{i}].entry_id", f"{eid!r} has two settings members")
            by_entry[eid] = s
        settings = [by_entry[e] for e in entries if e in by_entry]
        try:
            _check_settings_roi(settings, sensor_doc)
        except RunSpecError as e:
            raise ComposeError(recipe_name, "settings", str(e)) from e
        sensor = copy.deepcopy(sensor_doc["sensor"]) if inline_sensor else {"ref": dict(sensor_ref)}
    elif inline_sensor:
        raise ValueError("inline_sensor needs the sensor-spec document")
    else:
        sensor = {"ref": dict(sensor_ref)}

    _, scenario = layers["scenario"]
    _, profile = layers["engine_profile"]
    values = {"meta": recipe["meta"], "origin": profile["origin"], "collection": scenario["collection"],
              "sensor": sensor, "settings": settings, "fidelity": recipe["fidelity"]}
    if "extras" in profile:
        values["extras"] = profile["extras"]
    descriptor = {m: copy.deepcopy(values[m]) for m in DESCRIPTOR_ORDER if m in values}
    spec = {"spec_version": SPEC_VERSION, "descriptor": descriptor, "engine": copy.deepcopy(profile["engine"])}
    sources = {"spec_version": f"rules {RULES}"}
    sources.update({f"descriptor.{m}": layers[OWNER[m]][0] for m in descriptor if m != "sensor"})
    sources["descriptor.sensor"] = sensor_ref["name"]
    sources["engine"] = layers["engine_profile"][0]
    return spec, {k: sources[k] for k in ("spec_version", *(f"descriptor.{m}" for m in descriptor), "engine")}


def default_sensor_library(recipe_path):
    """`manifold_sensors/`, the sibling of the layer root (the folder holding `recipes/`)."""
    return Path(recipe_path).resolve().parent.parent.parent / "manifold_sensors"


def _compose(recipe_path, inline_sensor=False, sensor_library=None):
    recipe_path = Path(recipe_path).resolve()
    root = recipe_path.parent.parent
    library = Path(sensor_library).resolve() if sensor_library is not None else default_sensor_library(recipe_path)
    rel = lambda p: p.relative_to(root).as_posix()                  # noqa: E731
    files = {"recipe": recipe_path}
    recipe = _load_layer(recipe_path, rel(recipe_path))
    layers = {"recipe": (rel(recipe_path), recipe)}
    for kind in ("scenario", "engine_profile"):
        name = recipe.get(kind)
        if not isinstance(name, str):
            raise ComposeError(rel(recipe_path), kind, "missing or not a layer name")
        path = root / LAYER_DIR[kind] / f"{name}.yaml"
        files[kind] = path
        layers[kind] = (rel(path), _load_layer(path, rel(path)))
    sensor_name = recipe.get("sensor")
    if not isinstance(sensor_name, str):
        raise ComposeError(rel(recipe_path), "sensor", "missing or not a sensor-library file name")
    try:
        sensor_doc = load_sensor_spec(library, sensor_name)
    except RunSpecError as e:
        raise ComposeError(rel(recipe_path), "sensor", str(e)) from e
    sensor_path = library / sensor_name
    ref = {"name": sensor_name, "content_hash": sha256_file(sensor_path)}
    spec, sources = merge(layers, ref, sensor_doc, inline_sensor)
    label = f"{library.name}/{sensor_name}"
    paths = {**{layers[k][0]: p for k, p in files.items()}, sensor_name: sensor_path}
    explained = {member: {"layer": label if src == sensor_name else src,
                          "content_hash": sha256_file(paths[src]) if src in paths else None}
                 for member, src in sources.items()}
    return spec, explained


def compose(recipe_path, *, inline_sensor=False, sensor_library=None):
    """The `run-spec/1` dict the recipe composes to. `descriptor.sensor` is `{ref: {name, content_hash}}` (the hash
    of the sensor file's bytes), or the sensor-spec's `sensor` block in place with `inline_sensor`."""
    return _compose(recipe_path, inline_sensor, sensor_library)[0]


def explain(recipe_path, *, sensor_library=None):
    """Each member of the composed spec with the layer file it came from and that file's sha256:
    `{member: {"layer": <root-relative file>, "content_hash": ...}}`. Provenance stays here, not in the spec."""
    return _compose(recipe_path, False, sensor_library)[1]


def dump(spec, recipe_rel):
    """The generated file's text: the header line, then the spec. The same spec gives the same bytes."""
    return HEADER.format(recipe=recipe_rel) + "\n" + yaml.safe_dump(spec, sort_keys=False, allow_unicode=True,
                                                                     width=110, default_flow_style=False)
