# GENERATED by scripts/gen_models.py from api/schemas - do not edit
"""Typed models of the SDK API payloads (`api/schemas/`), generated by `scripts/gen_models.py`.

One frozen dataclass per object schema, with `from_dict` and `to_dict`. Do not edit: change the schema
and regenerate (`python scripts/gen_models.py`). Imports: the standard library only.
"""
from __future__ import annotations

import dataclasses
from typing import Literal

__all__ = ['ArtifactList', 'ArtifactRef', 'ComposeRequest', 'ComposeResponse', 'ComposeResponseRecipe', 'ComposeResponseRun', 'ComposeResponseRunProvenanceEntry', 'LibraryDocument', 'LibraryList', 'LibraryListItem', 'Problem', 'ProblemErrorEntry', 'RunStatus', 'SensorDocument', 'SubmitRunRequest', 'SubmitSweepRequest', 'SweepStatus', 'SweepStatusRecipe', 'ValidateRequest', 'ValidateResponse', 'ValidateResponseRun', 'ValidateResponseRunCheck']

class _Absent:
    """Marker for a key that was not present."""

    def __repr__(self):
        return "ABSENT"


ABSENT = _Absent()
_JSON = {"string": (str,), "integer": (int,), "number": (int, float), "boolean": (bool,), "object": (dict,),
         "array": (list, tuple), "null": (type(None),)}


def _check_type(value, types, where):
    """A value of one of the JSON `types`; booleans are not integers or numbers."""
    for t in types:
        if t in ("integer", "number") and isinstance(value, bool):
            continue
        if isinstance(value, _JSON[t]):
            return
    raise ValueError(f"{where or '/'}: expected {' or '.join(types)}, got {type(value).__name__}")


def _build(spec, value, where):
    """A JSON value converted by a field spec (see the classes' _FIELDS)."""
    kind = spec[0]
    if kind == "any":
        return value
    if kind == "nullable":
        return None if value is None else _build(spec[1], value, where)
    if kind == "scalar":
        _check_type(value, spec[1], where)
        if spec[2] is not None and value not in spec[2]:
            raise ValueError(f"{where or '/'}: {value!r} is not one of {list(spec[2])}")
        return value
    if kind == "dict":
        _check_type(value, ("object",), where)
        return dict(value)
    if kind == "array":
        _check_type(value, ("array",), where)
        return tuple(_build(spec[1], v, f"{where}/{i}") for i, v in enumerate(value))
    if kind == "map":
        _check_type(value, ("object",), where)
        return {k: _build(spec[1], v, f"{where}/{_escape(k)}") for k, v in value.items()}
    if kind == "model":
        _check_type(value, ("object",), where)
        return globals()[spec[1]]._from_dict(value, where)
    raise AssertionError(kind)


def _dump(spec, value):
    kind = spec[0]
    if value is None:
        return None
    if kind == "nullable":
        return _dump(spec[1], value)
    if kind == "array":
        return [_dump(spec[1], v) for v in value]
    if kind == "map":
        return {k: _dump(spec[1], v) for k, v in value.items()}
    if kind == "model":
        return value.to_dict()
    return value


def _escape(key):
    return str(key).replace("~", "~0").replace("/", "~1")


class _Model:
    """Shared behaviour of the generated models: `from_dict` and `to_dict`."""
    _FIELDS = ()                # (json key, attribute, spec, required, nullable)
    _CLOSED = True              # additionalProperties is false

    @classmethod
    def from_dict(cls, data):
        """Build the model from its JSON form (nested models included).

        Raises
        ------
        ValueError
            For an unknown key (when the schema allows none), a missing required key or a value of the wrong JSON
            type; the message starts with the JSON Pointer of the offending value.
        """
        return cls._from_dict(data, "")

    @classmethod
    def _from_dict(cls, data, where):
        if not isinstance(data, dict):
            raise ValueError(f"{where or '/'}: expected object, got {type(data).__name__}")
        known = {f[0] for f in cls._FIELDS}
        if cls._CLOSED:
            for key in data:
                if key not in known:
                    raise ValueError(f"{where}/{_escape(key)}: unknown key {key!r} for {cls.__name__}")
        kwargs, absent = {}, []
        for key, attr, spec, required, nullable in cls._FIELDS:
            if key not in data:
                if required:
                    raise ValueError(f"{where}/{_escape(key)}: missing required key {key!r} for {cls.__name__}")
                if nullable:
                    absent.append(key)
                continue
            kwargs[attr] = _build(spec, data[key], f"{where}/{_escape(key)}")
        obj = cls(**kwargs)
        object.__setattr__(obj, "_absent", frozenset(absent))
        object.__setattr__(obj, "_extra", {k: v for k, v in data.items() if k not in known})
        return obj

    def to_dict(self):
        """The JSON form: optional fields that are None are omitted (a nullable one only if it was absent when read)."""
        out = {}
        absent = getattr(self, "_absent", frozenset())
        for key, attr, spec, required, nullable in self._FIELDS:
            value = getattr(self, attr)
            if value is None and not required and (not nullable or key in absent):
                continue
            out[key] = _dump(spec, value)
        out.update(getattr(self, "_extra", {}))                # an open schema's extension members, as read
        return out


@dataclasses.dataclass(frozen=True)
class ArtifactList(_Model):
    """A run's artifact references.

    Attributes
    ----------
    run_id : str
        The run id.
    artifacts : tuple[ArtifactRef, ...]
        The artifacts produced so far.
    """
    run_id: str
    artifacts: tuple[ArtifactRef, ...]
    _FIELDS = (
        ('run_id', 'run_id', ('scalar', ('string',), None), True, False),
        ('artifacts', 'artifacts', ('array', ('model', 'ArtifactRef')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ArtifactRef(_Model):
    """A reference to one file a run produced. The SDK returns references, never bare file paths: a reference carries
    the file's content hash and type, so it stays meaningful away from the machine that wrote it and its bytes can
    be verified after download.

    Attributes
    ----------
    name : str
        The artifact's name, unique within its run, for example `run_spec.json`, `run_info.json` or `log_info.json`,
        or a per-capture product named `<base>-t<task>-c<capture>.img` (and `.img.hdr`) as the platform template
        writes it. It is the last segment of the `get_artifact` path.
    sha256 : str
        The sha256 of the artifact's bytes, as 64 lowercase hex digits. The bytes returned by `get_artifact`, or
        read from `uri`, must hash to this value.
    media_type : str
        The media type of the bytes, for example `application/json` for a run spec or a log, `application/octet-
        stream` for an ENVI image and `text/plain` for its header.
    uri : str
        Where the bytes can be read: a `file://` URI when the run was executed locally, or a download URL when it
        was executed by a server.
    frame : int, optional
        For an artifact that belongs to one capture of a multi-frame run (an image, its header, a truth product),
        the zero-based index of that capture, in task order. Absent for an artifact that belongs to the run as a
        whole (the run spec, the engine logs).
    """
    name: str
    sha256: str
    media_type: str
    uri: str
    frame: int = None
    _FIELDS = (
        ('name', 'name', ('scalar', ('string',), None), True, False),
        ('sha256', 'sha256', ('scalar', ('string',), None), True, False),
        ('media_type', 'media_type', ('scalar', ('string',), None), True, False),
        ('uri', 'uri', ('scalar', ('string',), None), True, False),
        ('frame', 'frame', ('scalar', ('integer',), None), False, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ComposeRequest(_Model):
    """A request to compose a recipe into run specs. Give the recipe either by its name in the library or as a
    document; exactly one of the two. Composition is pure: it creates nothing and the same request always gives the
    same response.

    Attributes
    ----------
    recipe_name : str, optional
        The name of a recipe in the library: its file stem, as `list_recipes` returns it, for example
        `sensor_sweep_tahoe`.
    recipe : dict, optional
        A recipe document (`compose: compose/1`). The layers it names (scenario, engine profile, sensors) are read
        from the library.
    inline_sensor : bool, optional
        If true, each run spec carries its sensor block in place instead of a reference to the sensor file by name
        and content hash. The run id is the same either way.
    max_runs : int, optional
        The most runs the recipe may compose to; a sweep with more is a composition error. At most 32.
    """
    recipe_name: str = None
    recipe: dict = None
    inline_sensor: bool = None
    max_runs: int = None
    _FIELDS = (
        ('recipe_name', 'recipe_name', ('scalar', ('string',), None), False, False),
        ('recipe', 'recipe', ('dict',), False, False),
        ('inline_sensor', 'inline_sensor', ('scalar', ('boolean',), None), False, False),
        ('max_runs', 'max_runs', ('scalar', ('integer',), None), False, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ComposeResponse(_Model):
    """The run specs a recipe composes to, one per sensor, each with its run id and the provenance of each of its
    members. A recipe naming one sensor gives one run.

    Attributes
    ----------
    sweep_id : str
        The sweep id the runs would be submitted under: the sha256 of the canonical JSON serialization (RFC 8785) of
        their sorted run ids. Present for a one-run recipe too. It is not written into any run spec.
    recipe : ComposeResponseRecipe
        The recipe that was composed.
    is_sweep : bool
        True if the recipe names a list of sensors (`sensors`), false if it names one (`sensor`).
    runs : tuple[ComposeResponseRun, ...]
        One entry per run, in the order of the recipe's sensor list.
    """
    sweep_id: str
    recipe: ComposeResponseRecipe
    is_sweep: bool
    runs: tuple[ComposeResponseRun, ...]
    _FIELDS = (
        ('sweep_id', 'sweep_id', ('scalar', ('string',), None), True, False),
        ('recipe', 'recipe', ('model', 'ComposeResponseRecipe'), True, False),
        ('is_sweep', 'is_sweep', ('scalar', ('boolean',), None), True, False),
        ('runs', 'runs', ('array', ('model', 'ComposeResponseRun')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class LibraryDocument(_Model):
    """One library resource as authored.

    Attributes
    ----------
    name : str
        The name a recipe uses for the resource.
    sha256 : str
        The sha256 of the resource file's bytes, 64 lowercase hex digits.
    document : dict
        The parsed YAML document.
    """
    name: str
    sha256: str
    document: dict
    _FIELDS = (
        ('name', 'name', ('scalar', ('string',), None), True, False),
        ('sha256', 'sha256', ('scalar', ('string',), None), True, False),
        ('document', 'document', ('dict',), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class LibraryList(_Model):
    """The resources of one kind in the library.

    Attributes
    ----------
    items : tuple[LibraryListItem, ...]
        One entry per resource, sorted by name.
    """
    items: tuple[LibraryListItem, ...]
    _FIELDS = (
        ('items', 'items', ('array', ('model', 'LibraryListItem')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class Problem(_Model):
    """The one error model of the SDK: a problem details object (RFC 9457), served over REST with media type
    `application/problem+json` and raised in Python as an exception that carries the same members. An error caused
    by an authored file names that file (`layer`) and the field in it (`field`), so the user is pointed at the YAML
    they wrote, not at the composed document.

    Attributes
    ----------
    type : str
        A URI reference identifying the kind of problem. This contract defines `urn:protodirsig:problem:compose` (a
        recipe does not compose), `urn:protodirsig:problem:admission` (a submission failed admission),
        `urn:protodirsig:problem:not-found` (an unknown id or name), `urn:protodirsig:problem:invalid-request` (a
        request body that does not match its schema, or a request the SDK cannot act on as given) and
        `urn:protodirsig:problem:execution` (an accepted run failed while executing; status 500).
    title : str
        A short, human-readable summary of the kind of problem. It is the same for every occurrence of a `type`.
    status : int
        The HTTP status code of the response: 422 for composition, validation and admission errors, 404 for an
        unknown id or name, 500 for a run that failed while executing.
    detail : str, optional
        A human-readable explanation of this occurrence, written for the user who has to fix it.
    instance : str, optional
        A URI reference identifying this occurrence, for example the request path.
    layer : str | None, optional
        The authored file at fault, relative to the library root, for example `scenarios/tahoe_static_pose.yaml` or
        `manifold_sensors/auror-nir.yaml`. Null when no single file is at fault.
    field : str | None, optional
        The field at fault within `layer`, as a dotted path with list indices in brackets, for example `fidelity` or
        `sensors[1]`. Null when the whole file is at fault (for example, it does not parse) or no field can be
        named.
    errors : tuple[ProblemErrorEntry, ...], optional
        For a sweep that failed admission: one entry per run that failed, each naming the run and the authored file
        and field at fault. A sweep is admitted as a whole, so every failing run is reported at once.
    """
    type: str
    title: str
    status: int
    detail: str = None
    instance: str = None
    layer: str | None = None
    field: str | None = None
    errors: tuple[ProblemErrorEntry, ...] = None
    _FIELDS = (
        ('type', 'type', ('scalar', ('string',), None), True, False),
        ('title', 'title', ('scalar', ('string',), None), True, False),
        ('status', 'status', ('scalar', ('integer',), None), True, False),
        ('detail', 'detail', ('scalar', ('string',), None), False, False),
        ('instance', 'instance', ('scalar', ('string',), None), False, False),
        ('layer', 'layer', ('nullable', ('scalar', ('string',), None)), False, True),
        ('field', 'field', ('nullable', ('scalar', ('string',), None)), False, True),
        ('errors', 'errors', ('array', ('model', 'ProblemErrorEntry')), False, False),
    )
    _CLOSED = False


@dataclasses.dataclass(frozen=True)
class RunStatus(_Model):
    """The state of one run, as returned by `submit_run`, `get_run` and `cancel_run`, and for each run of a sweep by
    `submit_sweep` and `get_sweep`. A run exists only once it has been admitted, so a status is never `rejected`: a
    submission that fails admission is answered with a problem instead.

    Attributes
    ----------
    run_id : str
        The run id: the sha256, as 64 lowercase hex digits, of the canonical JSON serialization (RFC 8785) of the
        resolved run spec, that is, the run spec with its sensor block materialized. The same run spec, with its
        sensor inline or by reference, always has the same run id.
    name : str
        The run's name, the `descriptor.meta.name` of its run spec. For a run of a sweep it is `<recipe
        name>--<sensor file stem>`.
    state : Literal['accepted', 'running', 'rendered', 'failed', 'cancelled']
        `accepted`: admitted and waiting to execute. `running`: executing (the engine dry run of the assembled job,
        then the render). `rendered`: finished; all artifacts are available. `failed`: execution stopped with an
        error, given in `errors`. `cancelled`: cancelled before it finished. `rendered`, `failed` and `cancelled`
        are final.
    errors : tuple[Problem, ...]
        For a `failed` run, the problems that stopped it; empty otherwise.
    artifacts : tuple[ArtifactRef, ...]
        References to the artifacts the run has produced so far: the resolved run spec from acceptance, the engine's
        logs once written, and the image, its header and the truth images once the run has `rendered`. The same list
        `list_artifacts` returns.
    """
    run_id: str
    name: str
    state: Literal['accepted', 'running', 'rendered', 'failed', 'cancelled']
    errors: tuple[Problem, ...]
    artifacts: tuple[ArtifactRef, ...]
    _FIELDS = (
        ('run_id', 'run_id', ('scalar', ('string',), None), True, False),
        ('name', 'name', ('scalar', ('string',), None), True, False),
        ('state', 'state', ('scalar', ('string',), ('accepted', 'running', 'rendered', 'failed', 'cancelled')), True, False),
        ('errors', 'errors', ('array', ('model', 'Problem')), True, False),
        ('artifacts', 'artifacts', ('array', ('model', 'ArtifactRef')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class SensorDocument(_Model):
    """One library sensor as authored.

    Attributes
    ----------
    name : str
        The sensor file's name, as a recipe names it.
    sha256 : str
        The sha256 of the sensor file's bytes, 64 lowercase hex digits.
    document : dict
        (no description)
    """
    name: str
    sha256: str
    document: dict
    _FIELDS = (
        ('name', 'name', ('scalar', ('string',), None), True, False),
        ('sha256', 'sha256', ('scalar', ('string',), None), True, False),
        ('document', 'document', ('dict',), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class SubmitRunRequest(_Model):
    """A run to submit: exactly one of a run spec, a recipe name or a recipe document; a recipe must name one sensor.

    Attributes
    ----------
    run_spec : dict, optional
        (no description)
    recipe_name : str, optional
        The name of a recipe in the library (its file stem).
    recipe : dict, optional
        A recipe document (`compose: compose/1`), composed against the library.
    """
    run_spec: dict = None
    recipe_name: str = None
    recipe: dict = None
    _FIELDS = (
        ('run_spec', 'run_spec', ('dict',), False, False),
        ('recipe_name', 'recipe_name', ('scalar', ('string',), None), False, False),
        ('recipe', 'recipe', ('dict',), False, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class SubmitSweepRequest(_Model):
    """A sweep to submit: exactly one of a recipe name or a recipe document.

    Attributes
    ----------
    recipe_name : str, optional
        The name of a recipe in the library (its file stem).
    recipe : dict, optional
        A recipe document (`compose: compose/1`), composed against the library.
    max_runs : int, optional
        The most runs the recipe may compose to; at most 32.
    """
    recipe_name: str = None
    recipe: dict = None
    max_runs: int = None
    _FIELDS = (
        ('recipe_name', 'recipe_name', ('scalar', ('string',), None), False, False),
        ('recipe', 'recipe', ('dict',), False, False),
        ('max_runs', 'max_runs', ('scalar', ('integer',), None), False, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class SweepStatus(_Model):
    """The state of a sweep: one recipe composed into one run per sensor. A sweep has no state of its own; it reports
    the state of each of its runs, and a run that fails or is cancelled does not affect the others.

    Attributes
    ----------
    sweep_id : str
        The sweep id: the sha256, as 64 lowercase hex digits, of the canonical JSON serialization (RFC 8785) of the
        sorted array of the sweep's run ids. A sweep is identified by the runs it contains, so any recipe that
        composes to the same runs names the same sweep.
    recipe : SweepStatusRecipe
        The recipe the sweep was first submitted from.
    runs : tuple[RunStatus, ...]
        The status of each run, in the order of the recipe's sensor list.
    """
    sweep_id: str
    recipe: SweepStatusRecipe
    runs: tuple[RunStatus, ...]
    _FIELDS = (
        ('sweep_id', 'sweep_id', ('scalar', ('string',), None), True, False),
        ('recipe', 'recipe', ('model', 'SweepStatusRecipe'), True, False),
        ('runs', 'runs', ('array', ('model', 'RunStatus')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ValidateRequest(_Model):
    """A request to check whether runs would be admitted, without submitting them. Give exactly one of a run spec, a
    recipe name or a recipe document; a recipe is composed first and each of its runs is checked.

    Attributes
    ----------
    run_spec : dict, optional
        A `run-spec/1` document, with its sensor by reference or in place.
    recipe_name : str, optional
        The name of a recipe in the library (its file stem).
    recipe : dict, optional
        A recipe document (`compose: compose/1`), composed against the library.
    engine_check : Literal['none', 'dry_run'], optional
        `none`: the engine-free checks only (the run-spec schema, reference resolution, content-hash verification
        and the library files); pure, and needs no engine. These are the checks admission runs. `dry_run`: those
        checks and a DIRSIG dry run of the assembled job, which needs a local DIRSIG installation.
    """
    run_spec: dict = None
    recipe_name: str = None
    recipe: dict = None
    engine_check: Literal['none', 'dry_run'] = None
    _FIELDS = (
        ('run_spec', 'run_spec', ('dict',), False, False),
        ('recipe_name', 'recipe_name', ('scalar', ('string',), None), False, False),
        ('recipe', 'recipe', ('dict',), False, False),
        ('engine_check', 'engine_check', ('scalar', ('string',), ('none', 'dry_run')), False, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ValidateResponse(_Model):
    """The verdict for each run checked. A run is `valid` if every check performed passed; `engine_checked` says
    whether the engine dry run was among them, so a verdict made without the engine is never mistaken for one made
    with it.

    Attributes
    ----------
    engine_check : Literal['none', 'dry_run']
        The level that was requested: `none` or `dry_run`.
    runs : tuple[ValidateResponseRun, ...]
        One verdict per run, in the order of the recipe's sensor list; one entry for a run spec.
    """
    engine_check: Literal['none', 'dry_run']
    runs: tuple[ValidateResponseRun, ...]
    _FIELDS = (
        ('engine_check', 'engine_check', ('scalar', ('string',), ('none', 'dry_run')), True, False),
        ('runs', 'runs', ('array', ('model', 'ValidateResponseRun')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ComposeResponseRecipe(_Model):
    """The recipe that was composed.

    Attributes
    ----------
    name : str | None
        The recipe's name in the library, or null if it was given as a document.
    sha256 : str
        The sha256 of the recipe's bytes, as 64 lowercase hex digits.
    """
    name: str | None
    sha256: str
    _FIELDS = (
        ('name', 'name', ('nullable', ('scalar', ('string',), None)), True, True),
        ('sha256', 'sha256', ('scalar', ('string',), None), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ComposeResponseRun(_Model):
    """A model of the SDK API.

    Attributes
    ----------
    run_id : str
        The run id the run spec would be submitted under (see `run_status`).
    name : str
        The run's name, its `descriptor.meta.name`.
    sensor : str
        The sensor file the run uses, as named in the recipe, for example `auror-nir.yaml`.
    run_spec : dict
        The composed `run-spec/1` document. Its `descriptor.sensor` is a reference `{ref: {name, content_hash}}` or,
        with `inline_sensor`, the `sensor` block of a `sensor-spec/1` document. Every composed run spec validates
        against the run-spec schema.
    provenance : dict[str, ComposeResponseRunProvenanceEntry]
        For each member of the run spec (for example `descriptor.collection` or `engine`), the authored file it came
        from and that file's content hash. Provenance is returned beside the run spec, never inside it, and is not
        part of the run id.
    """
    run_id: str
    name: str
    sensor: str
    run_spec: dict
    provenance: dict[str, ComposeResponseRunProvenanceEntry]
    _FIELDS = (
        ('run_id', 'run_id', ('scalar', ('string',), None), True, False),
        ('name', 'name', ('scalar', ('string',), None), True, False),
        ('sensor', 'sensor', ('scalar', ('string',), None), True, False),
        ('run_spec', 'run_spec', ('dict',), True, False),
        ('provenance', 'provenance', ('map', ('model', 'ComposeResponseRunProvenanceEntry')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class LibraryListItem(_Model):
    """One library resource.

    Attributes
    ----------
    name : str
        The name a recipe uses for the resource.
    sha256 : str
        The sha256 of the resource file's bytes, 64 lowercase hex digits.
    """
    name: str
    sha256: str
    _FIELDS = (
        ('name', 'name', ('scalar', ('string',), None), True, False),
        ('sha256', 'sha256', ('scalar', ('string',), None), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ProblemErrorEntry(_Model):
    """A model of the SDK API.

    Attributes
    ----------
    run : str
        The run's name (its `meta.name`).
    detail : str
        Why the run failed admission.
    layer : str | None, optional
        The authored file at fault, relative to the library root, or null.
    field : str | None, optional
        The field at fault within `layer`, or null.
    """
    run: str
    detail: str
    layer: str | None = None
    field: str | None = None
    _FIELDS = (
        ('run', 'run', ('scalar', ('string',), None), True, False),
        ('detail', 'detail', ('scalar', ('string',), None), True, False),
        ('layer', 'layer', ('nullable', ('scalar', ('string',), None)), False, True),
        ('field', 'field', ('nullable', ('scalar', ('string',), None)), False, True),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class SweepStatusRecipe(_Model):
    """The recipe the sweep was first submitted from.

    Attributes
    ----------
    name : str | None
        The recipe's name in the library (its file stem), or null if the recipe was submitted as a document.
    sha256 : str
        The sha256 of the recipe's bytes, as 64 lowercase hex digits.
    """
    name: str | None
    sha256: str
    _FIELDS = (
        ('name', 'name', ('nullable', ('scalar', ('string',), None)), True, True),
        ('sha256', 'sha256', ('scalar', ('string',), None), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ValidateResponseRun(_Model):
    """A model of the SDK API.

    Attributes
    ----------
    name : str | None
        The run's name, its `descriptor.meta.name`, or null if the run spec has none.
    run_id : str | None
        The run id the run spec would be submitted under, or null if the run spec could not be resolved (its sensor
        could not be materialized).
    valid : bool
        True if every check performed passed.
    engine_checked : bool
        True only if the DIRSIG dry run was performed. False at `engine_check: none`, and false at `dry_run` if the
        dry run could not be attempted because an earlier check failed.
    checks : tuple[ValidateResponseRunCheck, ...]
        The outcome of each check, in the order they run. A check that was not performed is absent.
    """
    name: str | None
    run_id: str | None
    valid: bool
    engine_checked: bool
    checks: tuple[ValidateResponseRunCheck, ...]
    _FIELDS = (
        ('name', 'name', ('nullable', ('scalar', ('string',), None)), True, True),
        ('run_id', 'run_id', ('nullable', ('scalar', ('string',), None)), True, True),
        ('valid', 'valid', ('scalar', ('boolean',), None), True, False),
        ('engine_checked', 'engine_checked', ('scalar', ('boolean',), None), True, False),
        ('checks', 'checks', ('array', ('model', 'ValidateResponseRunCheck')), True, False),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ComposeResponseRunProvenanceEntry(_Model):
    """A model of the SDK API.

    Attributes
    ----------
    layer : str
        The authored file, relative to the library root, or `rules compose/1` for a member the composition rules
        supply.
    content_hash : str | None
        `sha256:` followed by the file's 64-hex-digit hash, or null for a member the rules supply.
    """
    layer: str
    content_hash: str | None
    _FIELDS = (
        ('layer', 'layer', ('scalar', ('string',), None), True, False),
        ('content_hash', 'content_hash', ('nullable', ('scalar', ('string',), None)), True, True),
    )
    _CLOSED = True


@dataclasses.dataclass(frozen=True)
class ValidateResponseRunCheck(_Model):
    """A model of the SDK API.

    Attributes
    ----------
    check : Literal['schema', 'resolution', 'content_hash', 'library_files', 'dry_run']
        `schema`: the document is valid `run-spec/1`. `resolution`: every reference resolves to a library file.
        `content_hash`: each referenced file matches its stamped content hash. `library_files`: the files the run
        needs are present and match. `dry_run`: DIRSIG accepts the assembled job.
    passed : bool
        True if the check passed.
    errors : tuple[Problem, ...]
        Why the check failed, each with the authored file and field at fault where they can be named; empty if it
        passed.
    """
    check: Literal['schema', 'resolution', 'content_hash', 'library_files', 'dry_run']
    passed: bool
    errors: tuple[Problem, ...]
    _FIELDS = (
        ('check', 'check', ('scalar', ('string',), ('schema', 'resolution', 'content_hash', 'library_files', 'dry_run')), True, False),
        ('passed', 'passed', ('scalar', ('boolean',), None), True, False),
        ('errors', 'errors', ('array', ('model', 'Problem')), True, False),
    )
    _CLOSED = True
