#!/usr/bin/env python3
"""Compose manifold_run_specs/<name>.yaml from every manifold_run_specs/recipes/<name>.yaml (rules compose/1).

    python scripts/compose.py                      write every generated run spec
    python scripts/compose.py --check              list stale or missing generated files, exit 1 if any (CI)
    python scripts/compose.py --inline-sensor      write descriptor.sensor inline instead of as a ref
    python scripts/compose.py --explain <recipe>   print each composed member, its layer file and that file's hash
    python scripts/compose.py --refresh-vectors    rewrite the equivalence vectors from the repository's layers

Generated files start with `# GENERATED by scripts/compose.py from recipes/<name>.yaml - do not edit` and are
tracked. The layers, the rules and the composer are in `protodirsig.compose`.
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from protodirsig.compose import compose, dump, explain  # noqa: E402

RUN_SPECS = ROOT / "manifold_run_specs"
VECTORS = ROOT / "manifold_contracts" / "vectors" / "compose"
EQUIVALENCE = ("auror_ref", "synthetic_vis")      # vectors that are copies of the repository's own recipes


def _write(path, data, changed):
    if not path.is_file() or path.read_bytes() != data:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        changed.append(path.relative_to(ROOT).as_posix())


def refresh_vectors():
    """Rewrite each equivalence vector (its layers and expected.yaml) and the vectors' copy of the sensors it names
    from the repository. Files a case no longer needs are removed. Idempotent; returns the paths changed."""
    import yaml
    changed = []
    for name in EQUIVALENCE:
        case, recipe = VECTORS / name, RUN_SPECS / "recipes" / f"{name}.yaml"
        doc = yaml.safe_load(recipe.read_text())
        want = {Path("recipes") / recipe.name: recipe,
                Path("scenarios") / f"{doc['scenario']}.yaml": RUN_SPECS / "scenarios" / f"{doc['scenario']}.yaml",
                Path("engine_profiles") / f"{doc['engine_profile']}.yaml":
                    RUN_SPECS / "engine_profiles" / f"{doc['engine_profile']}.yaml"}
        for rel, src in want.items():
            _write(case / rel, src.read_bytes(), changed)
        _write(case / "expected.yaml", dump(compose(recipe), f"recipes/{recipe.name}").encode(), changed)
        for path in sorted(p for p in case.rglob("*") if p.is_file()):
            if path.relative_to(case) not in want and path.name != "expected.yaml":
                path.unlink()
                changed.append(f"removed {path.relative_to(ROOT).as_posix()}")
        for d in sorted((p for p in case.rglob("*") if p.is_dir()), reverse=True):
            if not any(d.iterdir()):
                shutil.rmtree(d)
        sensors = doc["sensors"] if "sensors" in doc else [doc["sensor"]]
        for s in sensors:
            _write(VECTORS / "manifold_sensors" / s, (ROOT / "manifold_sensors" / s).read_bytes(), changed)
    return changed


def generated(inline_sensor=False):
    """(target path, text) for every recipe."""
    for recipe in sorted((RUN_SPECS / "recipes").glob("*.yaml")):
        rel = recipe.relative_to(RUN_SPECS).as_posix()
        yield RUN_SPECS / f"{recipe.stem}.yaml", dump(compose(recipe, inline_sensor=inline_sensor), rel)


def main(argv):
    if "--explain" in argv:
        i = argv.index("--explain")
        if i + 1 >= len(argv):
            print("--explain needs a recipe path", file=sys.stderr)
            return 2
        for member, src in explain(Path(argv[i + 1])).items():
            print(f"{member:24s} {src['layer']:48s} {src['content_hash'] or ''}")
        return 0
    if "--refresh-vectors" in argv:
        for c in refresh_vectors():
            print("refreshed " + c)
        return 0
    check, stale = "--check" in argv, []
    for path, text in generated("--inline-sensor" in argv):
        if not path.is_file() or path.read_text() != text:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.write_text(text)
    for s in stale:
        print(("stale  " if check else "wrote  ") + s)
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
