#!/usr/bin/env python3
"""Compose the run specs of every manifold_run_specs/recipes/<name>.yaml (rules compose/1).

    python scripts/compose.py                      write every generated run spec
    python scripts/compose.py --check              list stale, missing or orphaned generated files, exit 1 if any (CI)
    python scripts/compose.py --inline-sensor      write descriptor.sensor inline instead of as a ref
    python scripts/compose.py --explain <recipe>   print the sweep id and, per run, each member, its layer and hash
    python scripts/compose.py --refresh-vectors    rewrite the equivalence vectors from the repository's layers

A one-sensor recipe writes manifold_run_specs/<name>.yaml; a sweep recipe (`sensors`) writes one
manifold_run_specs/<name>--<sensor file stem>.yaml per run. Generated files start with
`# GENERATED by scripts/compose.py from recipes/<name>.yaml - do not edit` and are tracked. The layers, the rules
and the composer are in `protodirsig.compose`.
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from protodirsig.compose import HEADER, compose, compose_sweep, dump  # noqa: E402

RUN_SPECS = ROOT / "manifold_run_specs"
VECTORS = ROOT / "manifold_contracts" / "vectors" / "compose"
EQUIVALENCE = ("auror_ref", "synthetic_vis")      # vectors that are copies of the repository's own recipes


def _write(path, data, changed):
    if not path.is_file() or path.read_bytes() != data:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        changed.append(path.relative_to(ROOT).as_posix())


def refresh_vectors():
    """Rewrite each equivalence vector (its layers and expected.yaml) and the vectors' copy of the sensors it names
    from the repository. Files a case no longer needs are removed. Idempotent; returns the paths changed."""
    import yaml
    changed = []
    for name in EQUIVALENCE:
        case, recipe = VECTORS / name, RUN_SPECS / "recipes" / f"{name}.yaml"
        doc = yaml.safe_load(recipe.read_text())
        want = {Path("recipes") / recipe.name: recipe,
                Path("scenarios") / f"{doc['scenario']}.yaml": RUN_SPECS / "scenarios" / f"{doc['scenario']}.yaml",
                Path("engine_profiles") / f"{doc['engine_profile']}.yaml":
                    RUN_SPECS / "engine_profiles" / f"{doc['engine_profile']}.yaml"}
        for rel, src in want.items():
            _write(case / rel, src.read_bytes(), changed)
        _write(case / "expected.yaml", dump(compose(recipe), f"recipes/{recipe.name}").encode(), changed)
        for path in sorted(p for p in case.rglob("*") if p.is_file()):
            if path.relative_to(case) not in want and path.name != "expected.yaml":
                path.unlink()
                changed.append(f"removed {path.relative_to(ROOT).as_posix()}")
        for d in sorted((p for p in case.rglob("*") if p.is_dir()), reverse=True):
            if not any(d.iterdir()):
                shutil.rmtree(d)
        sensors = doc["sensors"] if "sensors" in doc else [doc["sensor"]]
        for s in sensors:
            _write(VECTORS / "manifold_sensors" / s, (ROOT / "manifold_sensors" / s).read_bytes(), changed)
    return changed


def generated(inline_sensor=False):
    """(target path, text) for every run of every recipe."""
    for recipe in sorted((RUN_SPECS / "recipes").glob("*.yaml")):
        sweep = compose_sweep(recipe, inline_sensor=inline_sensor)
        for name, spec in sweep.runs.items():
            yield RUN_SPECS / f"{sweep.files[name]}.yaml", dump(spec, sweep.recipe)


def orphans(targets):
    """Generated files in manifold_run_specs/ that no recipe produces any more."""
    marker = HEADER.split("{")[0]
    return [p for p in sorted(RUN_SPECS.glob("*.yaml")) if p not in targets and p.read_text().startswith(marker)]


def main(argv):
    if "--explain" in argv:
        i = argv.index("--explain")
        if i + 1 >= len(argv):
            print("--explain needs a recipe path", file=sys.stderr)
            return 2
        sweep = compose_sweep(Path(argv[i + 1]))
        print(f"sweep_id {sweep.sweep_id}  ({sweep.recipe}, {len(sweep.runs)} run{'s' if len(sweep.runs) != 1 else ''})")
        for name, sources in sweep.sources.items():
            print(f"run {name}  -> manifold_run_specs/{sweep.files[name]}.yaml")
            for member, src in sources.items():
                print(f"  {member:34s} {src['layer']:48s} {src['content_hash'] or ''}")
        return 0
    if "--refresh-vectors" in argv:
        for c in refresh_vectors():
            print("refreshed " + c)
        return 0
    check, stale, targets = "--check" in argv, [], set()
    for path, text in generated("--inline-sensor" in argv):
        targets.add(path)
        if not path.is_file() or path.read_text() != text:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.write_text(text)
    for s in stale:
        print(("stale  " if check else "wrote  ") + s)
    orphaned = orphans(targets)
    for p in orphaned:
        print(("orphan " if check else "removed ") + p.relative_to(ROOT).as_posix())
        if not check:
            p.unlink()
    return 1 if (check and (stale or orphaned)) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
