#!/usr/bin/env python3
"""Compose manifold_run_specs/<name>.yaml from every manifold_run_specs/recipes/<name>.yaml (rules compose/1).

    python scripts/compose.py                      write every generated run spec
    python scripts/compose.py --check              list stale or missing generated files, exit 1 if any (CI)
    python scripts/compose.py --inline-sensor      write descriptor.sensor inline instead of as a ref
    python scripts/compose.py --explain <recipe>   print each composed member, its layer file and that file's hash

Generated files start with `# GENERATED by scripts/compose.py from recipes/<name>.yaml - do not edit` and are
tracked. The layers, the rules and the composer are in `protodirsig.compose`.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from protodirsig.compose import compose, dump, explain  # noqa: E402

RUN_SPECS = ROOT / "manifold_run_specs"


def generated(inline_sensor=False):
    """(target path, text) for every recipe."""
    for recipe in sorted((RUN_SPECS / "recipes").glob("*.yaml")):
        rel = recipe.relative_to(RUN_SPECS).as_posix()
        yield RUN_SPECS / f"{recipe.stem}.yaml", dump(compose(recipe, inline_sensor=inline_sensor), rel)


def main(argv):
    if "--explain" in argv:
        i = argv.index("--explain")
        if i + 1 >= len(argv):
            print("--explain needs a recipe path", file=sys.stderr)
            return 2
        for member, src in explain(Path(argv[i + 1])).items():
            print(f"{member:24s} {src['layer']:48s} {src['content_hash'] or ''}")
        return 0
    check, stale = "--check" in argv, []
    for path, text in generated("--inline-sensor" in argv):
        if not path.is_file() or path.read_text() != text:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.write_text(text)
    for s in stale:
        print(("stale  " if check else "wrote  ") + s)
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
