#!/usr/bin/env python3
"""Generate `src/protodirsig/models.py`, typed models of the SDK API payloads, from `api/schemas/*.schema.json`.

    python scripts/gen_models.py            (re)write src/protodirsig/models.py
    python scripts/gen_models.py --check    exit 1 if the committed file differs from a fresh generation

One frozen dataclass per object schema. A top-level class is named from its schema file in CapWords
(`artifact_ref.schema.json` -> `ArtifactRef`); an inline object with `additionalProperties: false` becomes a nested
class named for its parent and field (`ComposeResponse.runs` items -> `ComposeResponseRun`; the map values of
`provenance` -> `ComposeResponseRunProvenanceEntry`). Fields follow `properties` in schema order, required fields
first; optional fields default to None. Types: `string` str, `integer` int, `number` float, `boolean` bool, `enum` and
`const` as `Literal[...]`, arrays as `tuple[...]`, `type: [X, "null"]` as `X | None`, a `$ref` to another API schema as
its class, an open object (no `additionalProperties: false`) and the documents typed by other schemas (`run-spec/1`,
`sensor-spec/1`) as `dict`, a map (`additionalProperties` a schema) as `dict[str, X]`. Each class has `from_dict(data)`
(nested models built; ValueError naming the JSON Pointer for an unknown key where `additionalProperties` is false, a
missing required key or a value of the wrong JSON type) and `to_dict()` (optional fields that are None are omitted;
required and nullable fields are kept, except a nullable optional field that was absent when read by `from_dict`).
An open top-level schema (`problem`: RFC 9457 allows extension members) keeps the members it does not
declare, as read, and writes them back. Docstrings are the schema descriptions in NumPy style. The schema keywords that constrain values without changing types
(`pattern`, `minimum`, `maxItems`, `format`, `oneOf` required-sets) are not checked: validate against the schema for
those. Standard library only.
"""
import json
import keyword
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "api" / "schemas"
OUT = ROOT / "src" / "protodirsig" / "models.py"
HEADER = "# GENERATED by scripts/gen_models.py from api/schemas - do not edit\n"
RESERVED = {"ProblemError"}                     # names that would read as the exception family (protodirsig.errors)
JSON_TYPES = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "object": "dict",
              "array": "tuple", "null": "None"}

RUNTIME = '''

class _Absent:
    """Marker for a key that was not present."""

    def __repr__(self):
        return "ABSENT"


ABSENT = _Absent()
_JSON = {"string": (str,), "integer": (int,), "number": (int, float), "boolean": (bool,), "object": (dict,),
         "array": (list, tuple), "null": (type(None),)}


def _check_type(value, types, where):
    """A value of one of the JSON `types`; booleans are not integers or numbers."""
    for t in types:
        if t in ("integer", "number") and isinstance(value, bool):
            continue
        if isinstance(value, _JSON[t]):
            return
    raise ValueError(f"{where or '/'}: expected {' or '.join(types)}, got {type(value).__name__}")


def _build(spec, value, where):
    """A JSON value converted by a field spec (see the classes' _FIELDS)."""
    kind = spec[0]
    if kind == "any":
        return value
    if kind == "nullable":
        return None if value is None else _build(spec[1], value, where)
    if kind == "scalar":
        _check_type(value, spec[1], where)
        if spec[2] is not None and value not in spec[2]:
            raise ValueError(f"{where or '/'}: {value!r} is not one of {list(spec[2])}")
        return value
    if kind == "dict":
        _check_type(value, ("object",), where)
        return dict(value)
    if kind == "array":
        _check_type(value, ("array",), where)
        return tuple(_build(spec[1], v, f"{where}/{i}") for i, v in enumerate(value))
    if kind == "map":
        _check_type(value, ("object",), where)
        return {k: _build(spec[1], v, f"{where}/{_escape(k)}") for k, v in value.items()}
    if kind == "model":
        _check_type(value, ("object",), where)
        return globals()[spec[1]]._from_dict(value, where)
    raise AssertionError(kind)


def _dump(spec, value):
    kind = spec[0]
    if value is None:
        return None
    if kind == "nullable":
        return _dump(spec[1], value)
    if kind == "array":
        return [_dump(spec[1], v) for v in value]
    if kind == "map":
        return {k: _dump(spec[1], v) for k, v in value.items()}
    if kind == "model":
        return value.to_dict()
    return value


def _escape(key):
    return str(key).replace("~", "~0").replace("/", "~1")


class _Model:
    """Shared behaviour of the generated models: `from_dict` and `to_dict`."""
    _FIELDS = ()                # (json key, attribute, spec, required, nullable)
    _CLOSED = True              # additionalProperties is false

    @classmethod
    def from_dict(cls, data):
        """Build the model from its JSON form (nested models included).

        Raises
        ------
        ValueError
            For an unknown key (when the schema allows none), a missing required key or a value of the wrong JSON
            type; the message starts with the JSON Pointer of the offending value.
        """
        return cls._from_dict(data, "")

    @classmethod
    def _from_dict(cls, data, where):
        if not isinstance(data, dict):
            raise ValueError(f"{where or '/'}: expected object, got {type(data).__name__}")
        known = {f[0] for f in cls._FIELDS}
        if cls._CLOSED:
            for key in data:
                if key not in known:
                    raise ValueError(f"{where}/{_escape(key)}: unknown key {key!r} for {cls.__name__}")
        kwargs, absent = {}, []
        for key, attr, spec, required, nullable in cls._FIELDS:
            if key not in data:
                if required:
                    raise ValueError(f"{where}/{_escape(key)}: missing required key {key!r} for {cls.__name__}")
                if nullable:
                    absent.append(key)
                continue
            kwargs[attr] = _build(spec, data[key], f"{where}/{_escape(key)}")
        obj = cls(**kwargs)
        object.__setattr__(obj, "_absent", frozenset(absent))
        object.__setattr__(obj, "_extra", {k: v for k, v in data.items() if k not in known})
        return obj

    def to_dict(self):
        """The JSON form: optional fields that are None are omitted (a nullable one only if it was absent when read)."""
        out = {}
        absent = getattr(self, "_absent", frozenset())
        for key, attr, spec, required, nullable in self._FIELDS:
            value = getattr(self, attr)
            if value is None and not required and (not nullable or key in absent):
                continue
            out[key] = _dump(spec, value)
        out.update(getattr(self, "_extra", {}))                # an open schema's extension members, as read
        return out
'''


def capwords(text):
    return "".join(w[:1].upper() + w[1:] for w in re.split(r"[^A-Za-z0-9]+", text) if w)


def singular(word):
    return word[:-1] if word.endswith("s") and not word.endswith("ss") else word


def attr_name(key):
    name = re.sub(r"\W", "_", key)
    return name + "_" if keyword.iskeyword(name) else name


class Generator:
    def __init__(self, folder):
        self.folder = Path(folder)
        self.files = sorted(self.folder.glob("*.schema.json"))
        self.docs = {p.name: json.loads(p.read_text()) for p in self.files}
        self.classes = []                       # (name, schema, description) in emission order
        self.names = set()

    def top_name(self, file):
        return capwords(file.removesuffix(".schema.json"))

    def is_model(self, schema):
        """An inline object becomes a class only when closed (`additionalProperties: false`)."""
        return schema.get("type") == "object" and "properties" in schema and schema.get("additionalProperties") is False

    @staticmethod
    def is_top_model(schema):
        """A schema file's object, open or closed, is a class (an open one keeps its extra members)."""
        return schema.get("type") == "object" and "properties" in schema

    def ref_spec(self, ref):
        """`(spec, annotation)` for a `$ref`: another API object schema is its class; anything else a dict."""
        file = ref.split("#")[0]
        if "/" not in file and file in self.docs and self.is_top_model(self.docs[file]):
            name = self.top_name(file)
            return ("model", name), name
        return ("dict",), "dict"

    def new_class(self, name, schema):
        if name in RESERVED or name in self.names:
            name += "Entry"
        self.names.add(name)
        self.classes.append((name, schema))
        return name

    def spec(self, schema, parent, key):
        """`(spec, annotation, nullable)` of a property schema."""
        if "$ref" in schema:
            spec, ann = self.ref_spec(schema["$ref"])
            return spec, ann, False
        types = schema.get("type")
        types = types if isinstance(types, list) else ([types] if types else [])
        nullable = "null" in types
        base = [t for t in types if t != "null"]
        if "const" in schema:
            spec, ann = ("scalar", tuple(base) or (self.json_type(schema["const"]),), (schema["const"],)), \
                f"Literal[{schema['const']!r}]"
        elif "enum" in schema:
            values = tuple(v for v in schema["enum"] if v is not None)
            jt = tuple(sorted({self.json_type(v) for v in values}))
            spec, ann = ("scalar", jt, values), "Literal[" + ", ".join(repr(v) for v in values) + "]"
            nullable = nullable or None in schema["enum"]
        elif base == ["array"]:
            item_spec, item_ann, item_null = self.spec(schema.get("items", {}), parent, singular(key))
            if item_null:
                item_spec, item_ann = ("nullable", item_spec), f"{item_ann} | None"
            spec, ann = ("array", item_spec), f"tuple[{item_ann}, ...]"
        elif base == ["object"] and self.is_model(schema):
            name = self.new_class(parent + capwords(key), schema)
            spec, ann = ("model", name), name
        elif base == ["object"] and isinstance(schema.get("additionalProperties"), dict) and "properties" not in schema:
            value_schema = schema["additionalProperties"]
            if self.is_model(value_schema):
                name = self.new_class(parent + capwords(key) + "Entry", value_schema)
                vspec, vann = ("model", name), name
            else:
                vspec, vann, vnull = self.spec(value_schema, parent, key)
            spec, ann = ("map", vspec), f"dict[str, {vann}]"
        elif base == ["object"] or not base and "properties" in schema:
            spec, ann = ("dict",), "dict"
        elif len(base) == 1 and base[0] in JSON_TYPES:
            spec, ann = ("scalar", (base[0],), None), JSON_TYPES[base[0]]
        elif base:
            spec, ann = ("scalar", tuple(base), None), " | ".join(JSON_TYPES[t] for t in base)
        else:
            spec, ann = ("any",), "object"
        if nullable:
            spec, ann = ("nullable", spec), f"{ann} | None"
        return spec, ann, nullable

    @staticmethod
    def json_type(value):
        return {bool: "boolean", int: "integer", float: "number", str: "string", type(None): "null"}[type(value)]

    def emit_class(self, name, schema):
        required = schema.get("required", [])
        props = schema.get("properties", {})
        fields = []
        for key, sub in props.items():
            spec, ann, nullable = self.spec(sub, name, key)
            fields.append((key, attr_name(key), spec, key in required, nullable, ann, sub.get("description", "")))
        ordered = [f for f in fields if f[3]] + [f for f in fields if not f[3]]
        lines = ["", "", "@dataclasses.dataclass(frozen=True)", f"class {name}(_Model):"]
        lines += self.docstring(schema.get("description", ""), ordered)
        for key, attr, spec, req, nullable, ann, _ in ordered:
            lines.append(f"    {attr}: {ann}" + ("" if req else " = None"))
        lines.append("    _FIELDS = (")
        lines += [f"        {(k, a, s, r, n)!r}," for k, a, s, r, n, _, _ in fields]
        lines.append("    )")
        lines.append(f"    _CLOSED = {schema.get('additionalProperties') is False!r}")
        return lines

    @staticmethod
    def docstring(description, fields):
        wrap = lambda text, indent: textwrap.fill(text, 116, initial_indent=indent, subsequent_indent=indent)  # noqa: E731
        out = ['    """' + (wrap(description, "    ").strip() if description else "A model of the SDK API."), ""]
        if fields:
            out += ["    Attributes", "    ----------"]
            for key, attr, spec, req, nullable, ann, desc in fields:
                out.append(f"    {attr} : {ann}" + ("" if req else ", optional"))
                out.append(wrap(desc or "(no description)", "        "))
        out.append('    """')
        return [ln.replace('"""', "'''") if i not in (0, len(out) - 1) else ln for i, ln in enumerate(out)]

    def generate(self):
        for file in self.files:
            schema = self.docs[file.name]
            if self.is_top_model(schema):
                self.new_class(self.top_name(file.name), schema)
        body, i = [], 0
        while i < len(self.classes):                    # nested classes are appended while emitting
            name, schema = self.classes[i]
            body += self.emit_class(name, schema)
            i += 1
        names = [n for n, _ in self.classes]
        head = [HEADER.rstrip("\n"), '"""Typed models of the SDK API payloads (`api/schemas/`), generated by `scripts/gen_models.py`.',
                "",
                "One frozen dataclass per object schema, with `from_dict` and `to_dict`. Do not edit: change the schema",
                'and regenerate (`python scripts/gen_models.py`). Imports: the standard library only.',
                '"""',
                "from __future__ import annotations",
                "",
                "import dataclasses",
                "from typing import Literal",
                "",
                "__all__ = " + repr(sorted(names))]
        return "\n".join(head) + RUNTIME + "\n".join(body) + "\n"


def generate(folder=SCHEMAS):
    return Generator(folder).generate()


def main(argv):
    text = generate()
    if "--check" in argv:
        if not OUT.is_file() or OUT.read_text() != text:
            print(f"stale: {OUT.relative_to(ROOT)} (regenerate with scripts/gen_models.py)")
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
