#!/usr/bin/env python3
"""Stamp or check `content_hash` on file refs in manifold_sensors/*.yaml and the manifold_run_specs/ layer files
(recipes/, scenarios/, engine_profiles/); verify them in the generated manifold_run_specs/*.yaml. stdlib only.

    python scripts/stamp_hashes.py            rewrite stale or placeholder hashes in place
    python scripts/stamp_hashes.py --check    list stale hashes, exit 1 if any (CI)

A generated run spec (header `# GENERATED by scripts/compose.py`) is never rewritten here: a stale hash in it is
reported, and `scripts/compose.py` regenerates it from the restamped layers.

A ref is `{name: <path>, content_hash: "<sha256:...>"}`. The name resolves as the loaders resolve it: a
sensor-spec ref (`*.yaml` without a directory) and spectral curves against `manifold_sensors/`; every other name
against `manifold_config_repo/`. A name that is not a single file (a `.scene` whose geometry and materials sit beside
it) is left as written, because one file's hash would not identify the asset. The hash is `sha256` of the
file bytes. MANIFOLD's canonical-JSON hash (Metadata_v02 §6.15) replaces it when the registry is built.
"""
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REF = re.compile(r'(\{name: )([^,}]+)(, content_hash: ")([^"]*)(")')
BLOCK_REF = re.compile(r'^(\s*)name: (\S+)\n\1content_hash: [\'"]?([^\'"\s]+)', re.M)   # yaml.safe_dump's block form
GENERATED = "# GENERATED by scripts/compose.py"
LAYERS = ("recipes", "scenarios", "engine_profiles")
SKIP_SUFFIX = (".scene",)


def resolve(name, in_sensors_file):
    name = name.strip()
    if name.endswith(SKIP_SUFFIX):
        return None
    candidates = [ROOT / "manifold_sensors" / name] if (in_sensors_file or name.startswith("spectral/") or
                                                ("/" not in name and name.endswith(".yaml"))) \
        else [ROOT / "manifold_config_repo" / name]
    return next((c for c in candidates if c.is_file()), None)


def digest(path):
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def verify_generated(path):
    """Stale stamped hashes in a generated run spec; placeholders and unresolvable names are skipped."""
    stale = []
    for m in BLOCK_REF.finditer(path.read_text()):
        target = resolve(m.group(2), False)
        if target is not None and "<hash>" not in m.group(3) and m.group(3) != digest(target):
            where = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
            stale.append(f"{where}: {m.group(2)} (regenerate with scripts/compose.py)")
    return stale


def process(path, write):
    text, stale = path.read_text(), []
    if text.startswith(GENERATED):
        return verify_generated(path)
    in_sensors = path.parent.name == "manifold_sensors"

    def sub(m):
        target = resolve(m.group(2), in_sensors)
        if target is None:
            return m.group(0)
        want = digest(target)
        if m.group(4) != want:
            stale.append(f"{path.relative_to(ROOT)}: {m.group(2).strip()}")
        return m.group(1) + m.group(2) + m.group(3) + want + m.group(5)
    new = REF.sub(sub, text)
    if write and new != text:
        path.write_text(new)
    return stale


def main(argv):
    check = "--check" in argv
    stale = []
    run_specs = ROOT / "manifold_run_specs"
    files = sorted((ROOT / "manifold_sensors").glob("*.yaml"))
    files += [f for d in LAYERS for f in sorted((run_specs / d).glob("*.yaml"))] + sorted(run_specs.glob("*.yaml"))
    for f in files:
        stale += process(f, write=not check)
    for s in stale:
        print(("stale  " if check else "stamped ") + s)
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
