#!/usr/bin/env python3
"""Stamp or check `content_hash` on file refs in manifold_sensors/*.yaml and the manifold_run_specs/ layer files
(recipes/, scenarios/, engine_profiles/); verify them in the generated manifold_run_specs/*.yaml. stdlib only.

    python scripts/stamp_hashes.py            rewrite stale or placeholder hashes in place
    python scripts/stamp_hashes.py --check    list stale hashes, exit 1 if any (CI)

A generated run spec (header `# GENERATED by scripts/compose.py`) is never rewritten here: a stale hash in it is
reported, and `scripts/compose.py` regenerates it from the restamped layers.

A ref is `{name: <path>, content_hash: "<sha256:...>"}`. The name resolves as the loaders resolve it: a
sensor-spec ref (`*.yaml` without a directory) and spectral curves against `manifold_sensors/`; every other name
against `manifold_config_repo/`. A file ref's hash is `sha256` of the file bytes. A `.scene` ref names a directory,
the scene directory that holds the `.scene` file with its geometry and materials (`scenes/<scene>/<scene>.scene`), and
its hash is the `dirhash/1` digest of that directory; so is a ref that names a directory of the library itself (a
pass-through demo directory, `demo_dirs/<Name>`) (`src/protodirsig/dirhash.py`, defined in
`manifold_contracts/README.md`), since one file's hash would not identify the asset. MANIFOLD's canonical-JSON hash
(Metadata_v02 §6.15) replaces the file hash when the registry is built.

`engine.generator.revision` in an engine-profile layer is the `dirfm` revision the run spec is generated for: a
placeholder (`<git-sha>`) is rewritten to the `dirfm` commit pinned in `external/pins.json`, and `--check` reports a
revision that differs from the pin, in a layer or in a generated run spec.
"""
import hashlib
import importlib.util
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("_dirhash", ROOT / "src" / "protodirsig" / "dirhash.py")
dirhash = importlib.util.module_from_spec(_spec)             # by path: stdlib only, no package import
_spec.loader.exec_module(dirhash)
REF = re.compile(r'(\{name: )([^,}]+)(, content_hash: ")([^"]*)(")')
BLOCK_REF = re.compile(r'^(\s*)name: (\S+)\n\1content_hash: [\'"]?([^\'"\s]+)', re.M)   # yaml.safe_dump's block form
GENERATED = "# GENERATED by scripts/compose.py"
REVISION = re.compile(r'(generator: \{[^}]*\brevision: ")([^"]*)(")')                 # an engine profile's flow form
BLOCK_REVISION = re.compile(r'^(\s*)generator:\n(?:\1\s+\S.*\n)*?\1\s+revision: [\'"]?([^\'"\s]+)', re.M)   # generated
LAYERS = ("recipes", "scenarios", "engine_profiles")


def resolve(name, in_sensors_file):
    """The file a ref names, or for a `.scene` ref the scene directory; None when it does not exist."""
    name = name.strip()
    if dirhash.is_directory_ref(name):
        scene = ROOT / "manifold_config_repo" / name
        return scene.parent if scene.is_file() else None
    if (ROOT / "manifold_config_repo" / name).is_dir():           # a pass-through directory (proposed): dirhash/1
        return ROOT / "manifold_config_repo" / name
    candidates = [ROOT / "manifold_sensors" / name] if (in_sensors_file or name.startswith("spectral/") or
                                                ("/" not in name and name.endswith(".yaml"))) \
        else [ROOT / "manifold_config_repo" / name]
    return next((c for c in candidates if c.is_file()), None)


def digest(path):
    if path.is_dir():
        return dirhash.directory_digest(path)
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def pinned_revision():
    """The `dirfm` commit pinned in external/pins.json."""
    return json.loads((ROOT / "external" / "pins.json").read_text())["dirfm"]["commit"]


def verify_generated(path):
    """Stale stamped hashes in a generated run spec (placeholders and unresolvable names are skipped), and a generator
    revision that differs from the pin."""
    stale = []
    text = path.read_text()
    for m in BLOCK_REVISION.finditer(text):
        if m.group(2) != pinned_revision():
            where = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
            stale.append(f"{where}: engine.generator.revision {m.group(2)} (regenerate with scripts/compose.py)")
    for m in BLOCK_REF.finditer(text):
        target = resolve(m.group(2), False)
        if target is not None and "<hash>" not in m.group(3) and m.group(3) != digest(target):
            where = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
            stale.append(f"{where}: {m.group(2)} (regenerate with scripts/compose.py)")
    return stale


def process(path, write):
    text, stale = path.read_text(), []
    if text.startswith(GENERATED):
        return verify_generated(path)
    in_sensors = path.parent.name == "manifold_sensors"

    def sub(m):
        target = resolve(m.group(2), in_sensors)
        if target is None:
            return m.group(0)
        want = digest(target)
        if m.group(4) != want:
            stale.append(f"{path.relative_to(ROOT)}: {m.group(2).strip()}")
        return m.group(1) + m.group(2) + m.group(3) + want + m.group(5)
    new = REF.sub(sub, text)
    if path.parent.name == "engine_profiles":
        def rev(m):
            pin = pinned_revision()
            if m.group(2) != pin:
                stale.append(f"{path.relative_to(ROOT)}: engine.generator.revision {m.group(2)}")
            return m.group(1) + pin + m.group(3)
        new = REVISION.sub(rev, new)
    if write and new != text:
        path.write_text(new)
    return stale


def main(argv):
    check = "--check" in argv
    stale = []
    run_specs = ROOT / "manifold_run_specs"
    files = sorted((ROOT / "manifold_sensors").glob("*.yaml"))
    files += [f for d in LAYERS for f in sorted((run_specs / d).glob("*.yaml"))] + sorted(run_specs.glob("*.yaml"))
    for f in files:
        stale += process(f, write=not check)
    for s in stale:
        print(("stale  " if check else "stamped ") + s)
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
